project:
  type: book
  output-dir: doc

book:
  title: "Python Stack"
  author: "Prof. Calvin"
  date: "1/9/2025"
  chapters:
    - index.qmd
    - VSCode.qmd
    - Books.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  cache: true